### ISSUE TITLE
Module build failed: TypeError: fileSystem.statSync is not a function

### ISSUE THREAD

**Issue by zhaotoday** [zhaotoday/webpack-website#1]
ERROR in ./src/projects/xxb/pages/details/scripts.js
Module build failed: TypeError: fileSystem.statSync is not a function
    at module.exports (E:\github\webpack-website\node_modules\babel-loader\lib\utils\exists.js:7:25)
    at find (E:\github\webpack-website\node_modules\babel-loader\lib\resolve-rc.js:13:9)
    at Object.module.exports (E:\github\webpack-website\node_modules\babel-loader\lib\index.js:113:132)

ERROR in ./src/projects/xxb/pages/helps/scripts.js
Module build failed: TypeError: fileSystem.statSync is not a function
    at module.exports (E:\github\webpack-website\node_modules\babel-loader\lib\utils\exists.js:7:25)
    at find (E:\github\webpack-website\node_modules\babel-loader\lib\resolve-rc.js:13:9)
    at Object.module.exports (E:\github\webpack-website\node_modules\babel-loader\lib\index.js:113:132)

ERROR in ./src/projects/xxb/pages/commons/scripts.js
Module build failed: TypeError: fileSystem.statSync is not a function
    at module.exports (E:\github\webpack-website\node_modules\babel-loader\lib\utils\exists.js:7:25)
    at find (E:\github\webpack-website\node_modules\babel-loader\lib\resolve-rc.js:13:9)
    at Object.module.exports (E:\github\webpack-website\node_modules\babel-loader\lib\index.js:113:132)

ERROR in ./src/projects/xxb/pages/index/scripts.js
Module build failed: TypeError: fileSystem.statSync is not a function
    at module.exports (E:\github\webpack-website\node_modules\babel-loader\lib\utils\exists.js:7:25)
    at find (E:\github\webpack-website\node_modules\babel-loader\lib\resolve-rc.js:13:9)
    at Object.module.exports (E:\github\webpack-website\node_modules\babel-loader\lib\index.js:113:132)

**Comment by zhaotoday** [comment]
参考：https://github.com/babel/babel-loader/issues/505
```
$ npm install babel-loader@7.1.1 --save-dev
```

**Comment by sgehrman** [comment]
Didn't solve it for me.  I tried 7.1.1 and 7.1.2
